### PR TITLE
bump protobuf.js to v7

### LINKED ISSUE #1196: Descriptors extension fails to take into account default values
I get the following error using `fromDescriptor`:

```
TypeError: Cannot read property 'add' of undefined
    at Function.fromDescriptor (node_modules/protobufjs/ext/descriptor/index.js:219:66)
    at Function.fromDescriptor (node_modules/protobufjs/ext/descriptor/index.js:92:42)
```

Here's the code that throws the exception:

```javascript
            if (descriptor.field[i].hasOwnProperty("oneofIndex")) // eslint-disable-line no-prototype-builtins
                type.oneofsArray[descriptor.field[i].oneofIndex].add(field);
```

The reason it's throwing an exception is that the `oneofIndex` property is present, but is set to its default value (`0`) - ie, it is effectively unset, but the above code fails to take that into account.

I've tried setting `defaults: false` when loading the file, it doesn't seem to help. The problem may be that I'm importing the `descriptor.proto` into a `proto3` syntax file, and so default values are being forced because there's no such thing as unset in `proto3`? It seems like the above code should be updated anyway to handle this in future.

### PR DESCRIPTION
**Pull request by jackkav**
Fixes https://github.com/protobufjs/protobuf.js/issues/1196

### CODE REVIEW

**Comment by jackkav** [comment]
@redhoyasa this should be ready to review now

**Comment by redhoyasa** [comment]
@jackkav looks good, but can you please help to check if there are any breaking changes in migrating protobuf v6 to v7?

**Comment by jackkav** [comment]
Yes protobufjs v7 and above no longer supports node 4, 6, 8, 10 (10 ended active support 3 years ago)
also newBuffer implementation is improved in a way which is technically breaking
```
-                test.same(obj.bytesVal, [], "should set bytesVal");
+                test.same(obj.bytesVal, protobuf.util.newBuffer(0), "should set bytesVal");
```
all seem appropriate breaking changes to follow here.

**Review by redhoyasa — APPROVED** [review]
LGTM, thanks @jackkav

**Comment by redhoyasa** [comment]
@jackkav please use [0.3.0](https://www.npmjs.com/package/grpc-reflection-js/v/0.3.0).

**Pull request merged**
